config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # for google auth
  # root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :homes
  resources :statistics
  resources :lichesses
  resources :qr_codes
  resources :attendences
  resources :chesses
  resources :personal_informations
  resources :documentation

  root 'homes#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/qr_code.rb
# frozen_string_literal: true

class QrCode < ApplicationRecord
  validates :qr_url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: 'incorrect url format' }
  validates :title, :qr_url, presence: true
end

app/controllers/qr_codes_controller.rb
# frozen_string_literal: true

class QrCodesController < ApplicationController
  before_action :set_qr_code, only: %i[show edit update destroy]
  before_action :authenticate_admin!

  # GET /qr_codes or /qr_codes.json
  def index
    @qr_codes = QrCode.all

    @qr_codes = QrCode.order(params[:sort])
  end

  # GET /qr_codes/1 or /qr_codes/1.json
  def show; end

  # GET /qr_codes/new
  def new
    @qr_code = QrCode.new
  end

  # GET /qr_codes/1/edit
  def edit; end

  # POST /qr_codes or /qr_codes.json
  def create
    @qr_code = QrCode.new(qr_code_params)

    respond_to do |format|
      if @qr_code.save
        format.html { redirect_to qr_code_url(@qr_code), notice: 'Qr code was successfully created.' }
        format.json { render :show, status: :created, location: @qr_code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @qr_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qr_codes/1 or /qr_codes/1.json
  def update
    respond_to do |format|
      if @qr_code.update(qr_code_params)
        format.html { redirect_to qr_code_url(@qr_code), notice: 'Qr code was successfully updated.' }
        format.json { render :show, status: :ok, location: @qr_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @qr_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qr_codes/1 or /qr_codes/1.json
  def destroy
    @qr_code.destroy

    respond_to do |format|
      format.html { redirect_to qr_codes_url, notice: 'Qr code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_qr_code
    @qr_code = QrCode.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def qr_code_params
    params.require(:qr_code).permit(:title, :qr_url)
  end
end

app/helpers/qr_codes_helper.rb
# frozen_string_literal: true

module QrCodesHelper
end

app/views/qr_codes/_form.html.erb
<%= form_with(model: qr_code) do |form| %>
  <% if qr_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qr_code.errors.count, "error") %> prohibited this qr_code from being saved:</h2>

      <ul>
        <% qr_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="center">
      <div class="font">
        <div class="field">
          <%= form.label :title %>
          <%= form.text_field :title %>
        </div>

        <div class="field">
          <%= form.label :qr_url %>
          <%= form.text_field :qr_url %>
        </div>

        <div class="old_button">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>

app/views/qr_codes/edit.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">
            <div class="header_all">
                <h1>Editing Qr Code</h1>
            </div>
            <br>
            <br>
            <%= render 'form', qr_code: @qr_code %>

            <%= link_to 'Show', @qr_code %> |
            <%= link_to 'Back', qr_codes_path %>
        </div>
    </div>
</div>

app/views/qr_codes/index.html.erb
<div class="center">
  <div class="background_color">
    <div class="font">

      <div class="header_all">
        <h1>Qr Codes</h1>
      </div>
      
      <table class="table_center">
        <tbody>
          <thead>
            <tr>
              <th><%= link_to "Title", :sort => "title" %></th>
              <th><%= link_to "Qr Code Link", :sort => "qr_url" %></th>
              <th colspan="3"></th>
            </tr>
          </thead>
        </tbody>

        <tbody>
          <% @qr_codes.each do |qr_code| %>
            <tr>
              <td><%= qr_code.title %></td>
              <td>
              <%= link_to "Qr Code Link", qr_code.qr_url, :target => "_blank" %>
              </td>
              <td><%= link_to 'Show', qr_code %></td>
              <td><%= link_to 'Edit', edit_qr_code_path(qr_code) %></td>
              <td><%= link_to 'Destroy', qr_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <br>
      <%= link_to 'New Qr Code', new_qr_code_path %>
      <br>
      <br>
      <%= link_to 'Back', homes_path %>
      <br>
        <br>
    </div>
  </div>
</div>

app/views/qr_codes/new.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">
            <div class="header_all">
                <h1>New Qr Code</h1>
            </div>
            <br>
            <br>
            <%= render 'form', qr_code: @qr_code %>

            <%= link_to 'Back', qr_codes_path %>
        </div>
    </div>
</div>

app/views/qr_codes/newQR.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">
            <div class="header_all">
                <h1>New Qr Code</h1>
            </div>

            <%= render 'form', qr_code: @qr_code %>

            <%= link_to 'Back', qr_codes_path %>
        </div>
    </div>
</div>

app/views/qr_codes/show.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">

          <p>
            <strong>Title</strong>
            <%= @qr_code.title %>
          </p>

          <p>
            <strong>Qr Code Link</strong>
            <%= @qr_code.qr_url %>
          </p>

          <%= link_to 'Edit', edit_qr_code_path(@qr_code) %> |
          <%= link_to 'Back', qr_codes_path %>
        </div>
      </div>
    </div>