config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # for google auth
  # root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :homes
  resources :statistics
  resources :lichesses
  resources :qr_codes
  resources :attendences
  resources :chesses
  resources :personal_informations
  resources :documentation

  root 'homes#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  before_action :authenticate_admin!
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/views/homes/index.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">
            <%=image_tag("logo.png", alt: "Logo", :size => "490x400")%>
            <h1>Home</h1>
            <br>
            <br>
            <%= link_to 'Personal Information', personal_informations_path %>
            <br>
            <br>
            <%= link_to 'Attendance', attendences_path %>
            <br>
            <br>
            <%= link_to 'QR Code', qr_codes_path %>
            <br>
            <br>
            <%= link_to 'Player Statistics', statistics_path %>
            <br>
            <br>
            <%= link_to 'Documentation', documentation_index_path %>
            <br>
            <br>
            <%= link_to "Sign Out", destroy_admin_session_path %>
            <br>
            <br>
        </div>
    </div>
</div>