config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # for google auth
  # root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :homes
  resources :statistics
  resources :lichesses
  resources :qr_codes
  resources :attendences
  resources :chesses
  resources :personal_informations
  resources :documentation

  root 'homes#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/personal_information.rb
# frozen_string_literal: true

class PersonalInformation < ApplicationRecord
  has_many :chesses
  has_many :lichesses

  belongs_to :attendence, optional: true

  validates :uin, length: { minimum: 9, maximum: 9 }, numericality: { only_integer: true }, uniqueness: { scope: :end_date }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: 'incorrect email format' }
  validates :discord_username, format: { with: /\A([\A[a-zA-Z,\s]+\z]+#[0-9]{4,})\Z/i, message: 'incorrect discord username format' }, allow_blank: true
  validates :chess_com_username, :lichess_org_username, length: { minimum: 2 }, allow_blank: true
  validates :uin, :first_name, :last_name, :email, :start_date, :end_date, presence: true
end

app/controllers/personal_informations_controller.rb
# frozen_string_literal: true

class PersonalInformationsController < ApplicationController
  before_action :authenticate_admin!, except: %i[new show create]
  before_action :set_personal_information, only: %i[show edit update destroy]

  # GET /personal_informations or /personal_informations.json
  def index
    @personal_informations = if params[:paid] == 'true'
                               PersonalInformation.where(membership: true)
                             else
                               PersonalInformation.where(membership: false)
                             end

    @personal_informations = PersonalInformation.order(params[:sort])
  end

  # GET /personal_informations/1 or /personal_informations/1.json
  def show; end

  # GET /personal_informations/new
  def new
    @personal_information = PersonalInformation.new
  end

  # GET /personal_informations/1/edit
  def edit; end

  # POST /personal_informations or /personal_informations.json
  def create
    @personal_information = PersonalInformation.new(personal_information_params)

    respond_to do |format|
      if @personal_information.save
        format.html { redirect_to personal_information_url(@personal_information), notice: 'Personal information was successfully created.' }
        format.json { render :show, status: :created, location: @personal_information }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @personal_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_informations/1 or /personal_informations/1.json
  def update
    respond_to do |format|
      if @personal_information.update(personal_information_params)
        format.html { redirect_to personal_information_url(@personal_information), notice: 'Personal information was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_information }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @personal_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_informations/1 or /personal_informations/1.json
  def destroy
    @personal_information.destroy

    respond_to do |format|
      format.html { redirect_to personal_informations_url, notice: 'Personal information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def semester_start
    # use instance variable to communicate with V
  end

  def semester_end
    # use instance variable to communicate with V
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_personal_information
    @personal_information = PersonalInformation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def personal_information_params
    params.require(:personal_information).permit(:uin, :first_name, :last_name, :email, :membership, :start_date, :end_date, :discord_username, :chess_com_username, :lichess_org_username)
  end
end

app/helpers/personal_informations_helper.rb
# frozen_string_literal: true

module PersonalInformationsHelper
end

app/views/personal_informations/_form.html.erb
        <%= form_with(model: personal_information) do |form| %>
          <% if personal_information.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(personal_information.errors.count, "error") %> prohibited this personal_information from being saved:</h2>

              <ul>
                <% personal_information.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

  
          <div class="field">
            <%= form.label :uin %>
            <%= form.text_field :uin %>
          </div>

          <div class="field">
            <%= form.label :first_name %>
            <%= form.text_field :first_name %>
          </div>  

          <div class="field">
            <%= form.label :last_name %>
            <%= form.text_field :last_name %>
          </div>  

          <div class="field">
            <%= form.label :email %>
            <%= form.text_field :email %>
          </div>  

          <div class="field">
            <%= form.label :discord_username %>
            <%= form.text_field :discord_username %>
          </div>  

          <div hidden class="field">
            <%= form.label :membership %>
            <%= form.check_box :membership %>
          </div>  

          <div hidden class="field_date" >
            <%= form.label :start_date %>
            <% t = Time.now %>
            <% x = t.strftime('%Y') %>

            <% if t.mon < 8  %>
              <% x = x + '-01-01' %>
            <% else %>
              <% x = x + '-08-01' %>
            <% end %>
            
            <%= form.date_field :start_date, :value => x %>
            
          </div>  

          <div hidden class="field_date">
            <%= form.label :end_date %>
            <% t = Time.now %>
            <% x = t.strftime('%Y') %>

            <% if t.mon < 8  %>
              <% x = x + '-06-01' %>
            <% else %>
              <% x = x + '-12-31' %>
            <% end %>
            
            <%= form.date_field :end_date, :value => x %>
          </div>  


          <div class="field">
            <%= form.label :chess_com_username %>
            <%= form.text_field :chess_com_username %>
          </div>  

          <div class="field">
            <%= form.label :lichess_org_username %>
            <%= form.text_field :lichess_org_username %>
          </div>  

          <div class="old_button">
            <%= form.submit %>
          </div>
        <% end %>
      

app/views/personal_informations/_form1.html.erb
          <%= form_with(model: personal_information) do |form| %>
            <% if personal_information.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(personal_information.errors.count, "error") %> prohibited this personal_information from being saved:</h2>

                <ul>
                  <% personal_information.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= form.label :uin %>
              <%= form.text_field :uin %>
            </div>

            <div class="field">
              <%= form.label :first_name %>
              <%= form.text_field :first_name %>
            </div>  

            <div class="field">
              <%= form.label :last_name %>
              <%= form.text_field :last_name %>
            </div>  

            <div class="field">
              <%= form.label :email %>
              <%= form.text_field :email %>
            </div>  

            <div class="field">
              <%= form.label :discord_username %>
              <%= form.text_field :discord_username %>
            </div>  

            <div class="field">
              <%= form.label :membership %>
              <%= form.check_box :membership %>
            </div>  

            <div class="field_date" >
              <%= form.label :start_date %>
              <% t = Time.now %>
              <% x = t.strftime('%Y') %>

              <% if t.mon < 8  %>
                <% x = x + '-01-01' %>
              <% else %>
                <% x = x + '-08-01' %>
              <% end %>
              
              <%= form.date_field :start_date, :value => x %>
              
            </div>  

            <div class="field_date">
              <%= form.label :end_date %>
              <% t = Time.now %>
              <% x = t.strftime('%Y') %>

              <% if t.mon < 8  %>
                <% x = x + '-06-01' %>
              <% else %>
                <% x = x + '-12-30' %>
              <% end %>
              
              <%= form.date_field :end_date, :value => x %>
            </div>  


            <div class="field">
              <%= form.label :chess_com_username %>
              <%= form.text_field :chess_com_username %>
            </div>  

            <div class="field">
              <%= form.label :lichess_org_username %>
              <%= form.text_field :lichess_org_username %>
            </div>  

            <div class="old_button">
              <%= form.submit %>
            </div>
          <% end %>
        

app/views/personal_informations/edit.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">
            <div class="header_all">
              <h1>Editing Personal Information</h1>
            </div>
            <br>
            <br>

            <%= render 'form1', personal_information: @personal_information %>

            <br>
        <br>
            <%= link_to 'Show', @personal_information %> 
            <br>
        <br>
            <%= link_to 'Back', personal_informations_path %>
            <br>
        <br>

        </div>
      </div>
    </div>

app/views/personal_informations/index.html.erb
<div class="center">
  <div class="background_color">
    <div class="font">
        <div class="header_all">
          <h1>Personal Information</h1>
         </div>

        <%= link_to "Show student with membership only", :paid => "true" %>
        <%= link_to "Show all students", :paid => "false" %>

        <br>
        <br>
          <table class="table_center">
            <thead>
              <tr>
                <th><%= link_to "Student UIN", :sort => "uin" %></th>
                <th><%= link_to "First Name", :sort => "first_name" %></th>
                <th><%= link_to "Last Name", :sort => "last_name" %></th>
                <th><%= link_to "Email", :sort => "email" %></th>
                <th><%= link_to "Membership", :sort => "membership" %></th>
                <th><%= link_to "Start Date", :sort => "start_date" %></th>
                <th><%= link_to "End Date", :sort => "end_date" %></th>
                <th><%= link_to "Discord Username", :sort => "discord_username" %></th>
                <th><%= link_to "Chess.com Username", :sort => "chess_com_username" %></th>
                <th><%= link_to "Lichess.org Username", :sort => "lichess_org_username" %></th>
                <th colspan="3"></th>
              </tr> 
            </thead>

            <tbody>
              <% @personal_informations.each do |personal_information| %>
                <tr>
                  <td><%= personal_information.uin %></td>
                  <td><%= personal_information.first_name %></td>
                  <td><%= personal_information.last_name %></td>
                  <td><%= personal_information.email %></td>
                  <td><%= personal_information.membership %></td>
                  <td><%= personal_information.start_date %></td>
                  <td><%= personal_information.end_date %></td>
                  <td><%= personal_information.discord_username %></td>
                  <td><%= personal_information.chess_com_username %></td>
                  <td><%= personal_information.lichess_org_username %></td>

                  <td><%= link_to 'Edit', edit_personal_information_path(personal_information) %></td>
                  <td><%= link_to 'Destroy', personal_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
        

        <br>
        <br>
        <%= link_to 'New', new_personal_information_path %>
        <br>
        <br>
        <%= link_to 'Back', homes_path %>
        <br>
      <br>
      </div>
    </div>
  </div>

app/views/personal_informations/new.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">

            <div class="header_all">
                <h1>New Member</h1>
            </div>
            <br>
            <br>
            <%= render 'form', personal_information: @personal_information %>
            <br>
            <br>
            <%= link_to 'Back', personal_informations_path %>
            <br>
            <br>
        </div>
    </div>
</div>

app/views/personal_informations/show.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">
          <p id="notice"><%= notice %></p>

          <p>
            <strong>UIN:</strong>
            <%= @personal_information.uin %>
          </p>

          <p>
            <strong>First Name:</strong>
            <%= @personal_information.first_name %>
          </p>

          <p>
            <strong>Last Name:</strong>
            <%= @personal_information.last_name %>
          </p>

          <p>
            <strong>Email:</strong>
            <%= @personal_information.email %>
          </p>

          <p>
            <strong>Discord Username:</strong>
            <%= @personal_information.discord_username %>
          </p>

          <p>
            <strong> Membership:</strong>
            <%= @personal_information.membership %>
          </p>

          <p>
            <strong>Start Date:</strong>
            <%= @personal_information.start_date %>
          </p>

          <p>
            <strong>End Date:</strong>
            <%= @personal_information.end_date %>
          </p>

          <p>
            <strong>Chess.com Username:</strong>
            <%= @personal_information.chess_com_username %>
          </p>

          <p>
            <strong>Lichess.org Username:</strong>
            <%= @personal_information.lichess_org_username %>
          </p>

          <br>
          <br>
          <%= link_to 'Back', personal_informations_path %>
          <br>
          <br>
        </div>
      </div>
    </div>