config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # for google auth
  # root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :homes
  resources :statistics
  resources :lichesses
  resources :qr_codes
  resources :attendences
  resources :chesses
  resources :personal_informations
  resources :documentation

  root 'homes#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attendence.rb
# frozen_string_literal: true

class Attendence < ApplicationRecord
  personal_informations = PersonalInformation.all
  has_many :personal_informations
  validates :uin, length: { minimum: 9, maximum: 9 }, numericality: { only_integer: true }, uniqueness: { scope: :day_of_event }
  validates :day_of_event, uniqueness: { scope: :uin }
  validates :uin, :day_of_event, presence: true
end

app/controllers/attendences_controller.rb
# frozen_string_literal: true

class AttendencesController < ApplicationController
  before_action :authenticate_admin!, except: %i[new show create]
  before_action :set_attendence, only: %i[show edit update destroy]
  # GET /attendences or /attendences.json
  def index
    @attendences = Attendence.all

    @attendences = Attendence.order(params[:sort])
  end

  # GET /attendences/1 or /attendences/1.json
  def show; end

  # GET /attendences/new
  def new
    @attendence = Attendence.new
  end

  # GET /attendences/1/edit
  def edit; end

  # POST /attendences or /attendences.json
  def create
    @attendence = Attendence.new(attendence_params)

    respond_to do |format|
      if @attendence.save
        format.html { redirect_to attendence_url(@attendence), notice: 'Attendence was successfully created.' }
        format.json { render :show, status: :created, location: @attendence }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendences/1 or /attendences/1.json
  def update
    respond_to do |format|
      if @attendence.update(attendence_params)
        format.html { redirect_to attendence_url(@attendence), notice: 'Attendence was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendence }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendences/1 or /attendences/1.json
  def destroy
    @attendence.destroy

    respond_to do |format|
      format.html { redirect_to attendences_url, notice: 'Attendence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_attendance_table
    t = Time.now
    x = t.strftime('%m%d')

    past_attendances = Attendence.all

    past_attendances.each(&:destroy) if %w[1231 0602].include?(x)
  end
  helper_method :update_attendance_table

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_attendence
    @attendence = Attendence.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def attendence_params
    params.require(:attendence).permit(:uin, :day_of_event)
  end
end

app/helpers/attendences_helper.rb
# frozen_string_literal: true

module AttendencesHelper
end

app/views/attendences/_form.html.erb
<%= form_with(model: attendence) do |form| %>
  <% if attendence.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(attendence.errors.count, 'error') %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="center">
      <div class="font">      
        <div class='field'>
          <%= form.label :uin %>
          <%= form.text_field :uin %>
        </div>

        <div hidden class='field_date' >
          <%= form.label :day_of_event %>
          <% t = Time.now %>
          <% x = t.strftime('%Y') %>
          <% x = x + '-' + t.strftime('%m') %>
          <% x = x + '-' + t.strftime('%d') %>
          <%= form.date_field :day_of_event, :value => x %>
        </div>  

        <div class="old_button">
          <%= form.submit %>
        </div>
      <% end %>
      </div>
  </div>

app/views/attendences/_form1.html.erb
<%= form_with(model: attendence) do |form| %>
  <% if attendence.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(attendence.errors.count, 'error') %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="center">

      <div class="font">        

  <div class='field'>
    <%= form.label :uin %>
    <%= form.text_field :uin %>
  </div>

  <div class='field_date' >
    <%= form.label :day_of_event %>
    <% t = Time.now %>
    <% x = t.strftime('%Y') %>
    <% x = x + '-' + t.strftime('%m') %>
    <% x = x + '-' + t.strftime('%d') %>
    <%= form.date_field :day_of_event, :value => x %>
  </div>  

  <div class="old_button">
    <%= form.submit %>
  </div>

  </div>
</div>
<% end %>

app/views/attendences/edit.html.erb
<div class="center">
    <div class="background_color">
        <div class="font">
        
        <div class="header_all">
            <h1>Editing Attendence</h1>
        </div>
        <br>
        <br>
        <%= render 'form1', attendence: @attendence %>
        <br>
        <br>
        <%= link_to 'Show', @attendence %>
        <br>
        <br>
        <%= link_to 'Back', attendences_path %>
        <br>
        <br>
        </div>
    </div>
</div>

app/views/attendences/index.html.erb
<div class="center">
  <div class="background_color">
    <div class="font">
      <p id='notice'><%= notice %></p>

      <div class="header_all">
        <h1>Attendances</h1>
      </div>
    <div class="line_chart">
      <%= column_chart Attendence.group(:day_of_event).count.sort_by {|k,v| k}.reverse[0..11], 
      xtitle: "Date" , 
      ytitle: "Attendance", colors: ["#FFF"], line_colors: ["#FFF"]%>
    </div>
    <br>
    <br>
    
          <table class="table_center">
            <thead>
              <tr>
                <th><%= link_to "Student UIN", :sort => "uin" %></th>
                <th><%= link_to "Date of Attendance", :sort => "day_of_event" %></th>
                <th colspan='3'></th>
              </tr>
            </thead>

            <tbody>
              <% update_attendance_table %>
              <% @attendences.each do |attendence| %>
                <tr>
                  <td><%= attendence.uin %></td>
                  <td><%= attendence.day_of_event %></td>
                  <td><%= link_to 'Edit', edit_attendence_path(attendence) %></td>
                  <td><%= link_to 'Destroy', attendence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

      <br>
      <br>
      <%= link_to 'New', new_attendence_path %>
      <br>
      <br>
      <%= link_to 'Back', homes_path %>
      <br>
      <br>

    </div>
  </div>
</div>

app/views/attendences/new.html.erb
<div class="center">
  <div class="background_color">
    <div class="font">
        <div class="header_all">
          <h1>New Attendence</h1>
        </div>
        <br>
        <br>
        <%= render 'form', attendence: @attendence %>
        <br>
        <br>
        <%= link_to 'Back', attendences_path %>
        <br>
        <br>
    </div>
  </div>
</div>

app/views/attendences/show.html.erb
<div class="center">
  <div class="background_color">
    <div class="font">
      <p id='notice'><%= notice %></p>

      <div class="header_all">
        <h1>Thank you for submitting your attendance</h1>
      </div>

      <p>
        <strong>Student UIN:</strong>
        <%= @attendence.uin %>
      </p>

      <p>
        <strong>Event Day:</strong>
        <%= @attendence.day_of_event %>
      </p>

<br>
        <br>
      <%= link_to 'Edit', edit_attendence_path(@attendence) %> 
      <br>
        <br>
      <%= link_to 'Back', attendences_path %>
      <br>
        <br>
    </div>
  </div>
</div> 